// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJC0cTqOGZYf2UO87kcvVUrRFOLbj50FI',
    appId: '1:294477280641:web:7fb7e9f56c7977582ba480',
    messagingSenderId: '294477280641',
    projectId: 'testchat-328e2',
    authDomain: 'testchat-328e2.firebaseapp.com',
    storageBucket: 'testchat-328e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkElNjQ0mqjwknICJ7O8SyLKx6TSEvHJ0',
    appId: '1:294477280641:android:be161b2a52748d552ba480',
    messagingSenderId: '294477280641',
    projectId: 'testchat-328e2',
    storageBucket: 'testchat-328e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-8lC3FM2yzq5QI4XXDU0TD5TLhRju_pc',
    appId: '1:294477280641:ios:d181cc00574bdbd82ba480',
    messagingSenderId: '294477280641',
    projectId: 'testchat-328e2',
    storageBucket: 'testchat-328e2.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-8lC3FM2yzq5QI4XXDU0TD5TLhRju_pc',
    appId: '1:294477280641:ios:63a7871955a070c42ba480',
    messagingSenderId: '294477280641',
    projectId: 'testchat-328e2',
    storageBucket: 'testchat-328e2.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
